name: Generate Templates

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git config
        run: |
          git config --global user.name "o306336202"
          git config --global user.email "o306336202@gmail.com"
          git config --global init.defaultBranch master
      - name: Generate Templates
        run: |
          git clone --branch master https://github.com/o306336202/templates.git master
          cd master
          chmod +x generate.sh
          ./generate.sh mixed.json config/mixed
          ./generate.sh tun_fakeip.json config/tun
          ./generate.sh tun_ipv4_only.json config/tun
      - name: Public Templates
        run: |
          cd master
          git add -A config
          git commit -m "Auto generate."
          git push
