name: Generate Templates

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Generate Templates
        run: |
          chmod +x generate.sh
          ./generate.sh mixed.json config/mixed
          ./generate.sh tun_fakeip.json config/tun
          ./generate.sh tun_ipv4_only.json config/tun
      - name: Public Templates
        run: |
          git add -A config
          git commit -m "Auto generate."
          git push
