name: Generate Templates

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global init.defaultBranch public
      - name: Generate Templates
        run: |
          curl -fsSLo generate.sh https://raw.githubusercontent.com/senzyo/sing-box-templates/master/generate.sh
          curl -fsSLo mixed.json https://raw.githubusercontent.com/senzyo/sing-box-templates/master/mixed.json
          curl -fsSLo tun_fakeip.json https://raw.githubusercontent.com/senzyo/sing-box-templates/master/tun_fakeip.json
          curl -fsSLo tun_ipv4_only.json https://raw.githubusercontent.com/senzyo/sing-box-templates/master/tun_ipv4_only.json
          chmod +x generate.sh
          ./generate.sh mixed.json mixed
          wait
          ./generate.sh tun_fakeip.json tun
          wait
          ./generate.sh tun_ipv4_only.json tun
      - name: Public Templates
        run: |
          git init
          git add -A mixed tun
          git commit -m "Generate"
          git remote add origin https://${{ secrets.PERSONAL_TOKEN }}@github.com/senzyo/sing-box-templates.git
          git push -uf origin public:public
